name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: companieshouse-test
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


    - name: Authenticate with service account
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' | jq '.' > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json


    - name: Set Project ID
      run: gcloud config set project companieshouse-test


    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy companieshouse-function \
        --CPU 1 \
        --memory 500 \
        --gen2 \
        --runtime python311 \
        --trigger-http \
        --entry-point gcloud_download_companieshouse_file \
        --region europe-central2 \
        --source ./gcloud/gcloud_functions


    - name: Add Invoker Priviliges to Function
      run: |
        gcloud functions add-invoker-policy-binding companieshouse-function \
        --region="europe-central2" \
        --member="allUsers"


    - name: Deploy workflow
      run: |
        gcloud workflows deploy AirPollutionWorkflow \
        --location europe-central2 \
        --source ./workflows/companieshouse_to_pubsub.yaml
